import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    map: {
        ...StyleSheet.absoluteFillObject,
    },
    backButton: {
        position: 'absolute',
        top: 60,
        left: 20,
        backgroundColor: '#FFFFFF',
        padding: 10,
        borderRadius: 25,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 5,
    },
    detailButton: {
        position: 'absolute',
        top: 60,
        right: 20,
        backgroundColor: '#FFFFFF',
        padding: 10,
        borderRadius: 25,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 5,
    },
    poiMarker: {
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: appColors.primary,
        borderWidth: 2,
        borderColor: '#FFFFFF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    poiMarkerSelected: {
        width: 16,
        height: 16,
        borderRadius: 8,
        borderWidth: 3,
        transform: [{ scale: 1.2 }],
    },
    destinationMarker: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    loadingContainer: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: [{ translateX: -50 }, { translateY: -50 }],
        alignItems: 'center',
        gap: 12,
    },
    loadingText: {
        color: '#1B1E28',
        fontSize: 14,
        fontWeight: '500',
    },
    floatingCard: {
        position: 'absolute',
        bottom: 100,
        left: 16,
        right: 16,
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 10,
    },
    floatingCardContent: {
        padding: 16,
    },
    floatingCardHeader: {
        marginBottom: 12,
    },
    floatingCardTitleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    floatingCardTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1B1E28',
        flex: 1,
        marginRight: 12,
    },
    floatingCardBody: {
        gap: 10,
    },
    floatingCardRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 10,
    },
    floatingCardText: {
        fontSize: 14,
        color: '#1B1E28',
        flex: 1,
        lineHeight: 20,
    },
    floatingCardFooter: {
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
    },
    floatingCardHint: {
        fontSize: 13,
        color: appColors.primary,
        fontWeight: '600',
        textAlign: 'center',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 40,
        maxHeight: '80%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#1B1E28',
        flex: 1,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 16,
        paddingHorizontal: 4,
    },
    infoText: {
        fontSize: 15,
        color: '#1B1E28',
        flex: 1,
        lineHeight: 22,
    },
    infoSection: {
        marginTop: 12,
        marginBottom: 20,
    },
    sectionLabel: {
        fontSize: 12,
        fontWeight: '700',
        color: '#7D848D',
        marginBottom: 8,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    descriptionText: {
        fontSize: 15,
        color: '#1B1E28',
        lineHeight: 22,
    },
    coordinatesText: {
        fontSize: 14,
        color: '#7D848D',
        fontFamily: 'monospace',
    },
    primaryButton: {
        flexDirection: 'row',
        backgroundColor: appColors.primary,
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        marginTop: 20,
    },
    primaryButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    secondaryButton: {
        flexDirection: 'row',
        backgroundColor: '#F5F5F5',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 12,
    },
    secondaryButtonText: {
        color: '#1B1E28',
        fontSize: 16,
        fontWeight: '600',
    },
});