import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    map: {
        ...StyleSheet.absoluteFillObject,
    },
    backButton: {
        position: 'absolute',
        top: 60,
        left: 20,
        backgroundColor: '#FFFFFF',
        padding: 10,
        borderRadius: 25,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 5,
    },
    detailButton: {
        position: 'absolute',
        top: 60,
        right: 20,
        backgroundColor: '#FFFFFF',
        padding: 10,
        borderRadius: 25,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 5,
    },
    poiMarker: {
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: '#FF678B',
        borderWidth: 2,
        borderColor: '#FFFFFF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    calloutContainer: {
        width: 220,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    calloutImage: {
        width: '100%',
        height: 100,
        borderRadius: 8,
        marginBottom: 8,
    },
    calloutInfo: {
        gap: 4,
    },
    calloutTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1B1E28',
    },
    calloutSubtitle: {
        fontSize: 12,
        color: '#7D848D',
    },
    calloutRating: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginTop: 2,
    },
    calloutRatingText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#1B1E28',
    },
});