import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        marginTop: 30,
        borderBottomColor: '#E0E0E0',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1B1E28',
    },
    cancelButtonText: {
        fontSize: 16,
        color: '#888',
        fontWeight: '500',
    },
    previewContainer: {
        height: 120,
        backgroundColor: '#F5F5F5',
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
    },
    selectedMediaList: {
        flex: 1,
    },
    selectedMediaListContent: {
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    selectedThumbnailWrapper: {
        width: 100,
        height: 100,
        marginRight: 8,
        borderRadius: 8,
        overflow: 'hidden',
        position: 'relative',
    },
    selectedThumbnailImage: {
        width: '100%',
        height: '100%',
    },
    selectedNumberContainer: {
        position: 'absolute',
        top: 4,
        right: 4,
        backgroundColor: appColors.primary,
        width: 24,
        height: 24,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    selectedNumberText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: 'bold',
    },
    videoOverlay: {
        position: 'absolute',
        bottom: 4,
        left: 4,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        paddingHorizontal: 6,
        paddingVertical: 4,
        borderRadius: 4,
    },
    noMediaPlaceholder: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    noMediaText: {
        color: '#A0A0A0',
        fontSize: 14,
    },
    captionInput: {
        minHeight: 100,
        padding: 16,
        fontSize: 16,
        color: '#1B1E28',
        textAlignVertical: 'top',
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
    },
    section: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
    },
    sectionLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1B1E28',
        marginBottom: 8,
    },
    visibilitySelector: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: '#F9F9F9',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        gap: 8,
    },
    visibilityText: {
        flex: 1,
        fontSize: 16,
        color: '#1B1E28',
    },
    dropdown: {
        marginTop: 4,
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    dropdownOption: {
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    dropdownOptionText: {
        fontSize: 16,
        color: '#1B1E28',
    },
    dropdownOptionTextSelected: {
        color: appColors.primary,
        fontWeight: '600',
    },
    dropdownItem: {
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
        flexDirection: 'row',
        alignItems: 'center',
    },
    dropdownItemText: {
        fontSize: 15,
        color: '#1B1E28',
    },

    locationTextContainer: {
        flex: 1,
    },
    locationName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1B1E28',
        marginBottom: 2,
    },
    locationAddress: {
        fontSize: 13,
        color: '#7D848D',
    },
    ratingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingVertical: 8,
    },
    bottomButtonsContainer: {
        flexDirection: 'row',
        padding: 16,
        gap: 12,
        borderTopWidth: 1,
        borderTopColor: '#E0E0E0',
        backgroundColor: '#FFFFFF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 8,
    },
    draftButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    draftButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#888',
    },
    publishButton: {
        flex: 2,
        paddingVertical: 14,
        borderRadius: 8,
        backgroundColor: appColors.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
    publishButtonDisabled: {
        backgroundColor: '#FFB0C1',
    },
    publishButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    locationInput: {
        backgroundColor: '#F5F5F5',
        padding: 12,
        borderRadius: 8,
        fontSize: 14,
        color: '#1B1E28',
        marginTop: 8,
    },
    inputDisabled: {
        backgroundColor: '#E8E8E8',
        color: '#A0A0A0',
    },
    hint: {
        fontSize: 12,
        color: '#888',
        marginTop: 4,
        fontStyle: 'italic',
    },
    locationDisplay: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: '#F5F5F5',
        borderRadius: 8,
        marginTop: 8,
        gap: 8,
    },
    locationText: {
        fontSize: 14,
        color: '#1B1E28',
        flex: 1,
    },
});