import { appColors } from '@/settings';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    container: {
        flex: 1,
        backgroundColor: '#ffffff',
    },
    headerContainer: {
        backgroundColor: '#FDEEF0',
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 10,
    },
    headerWave: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#F9FAFB',
        borderTopLeftRadius: 40,
        borderTopRightRadius: 40,
    },
    headerContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerProfile: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        paddingRight: 10,
        borderRadius: 45,
        paddingLeft: 2,
        paddingVertical: 2,
    },
    avatarContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#FFF',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
        overflow: 'hidden',
    },
    avatarImage: {
        width: '100%',
        height: '100%',
    },
    headerUsername: {
        fontSize: 16,
        fontFamily: 'SFUISemibold',
        color: '#1B1E28',
    },
    locationContainer: {
        marginTop: 20,
    },
    locationLabel: {
        fontSize: 14,
        fontFamily: 'SFUISemibold',
        color: '#ffffff',
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 5,
    },
    locationText: {
        fontSize: 18,
        fontFamily: 'SFUISemibold',
        color: '#1B1E28',
        marginLeft: 5,
        marginRight: 5,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF',
        borderRadius: 45,
        paddingHorizontal: 15,
        marginHorizontal: 20,
        marginVertical: 2,
        // marginTop: -30, 
        height: 60,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 3,
    },
    searchInput: {
        flex: 1,
        marginLeft: 10,
        fontSize: 16,
        fontFamily: 'SFUISemibold',
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        marginTop: 30,
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 20,
        fontFamily: 'SFUISemibold',
        color: '#1B1E28',
    },
    sectionViewAll: {
        fontSize: 14,
        fontFamily: 'SFUISemibold',
        color: '#FF7029', // Màu cam (từ ảnh cũ)
    },
    reelCard: {
        width: 250,
        height: 350,
        borderRadius: 20,
        marginRight: 15,
        overflow: 'hidden',
    },
    reelCardOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.2)',
        padding: 15,
        justifyContent: 'flex-end',
    },
    reelCardTitle: {
        fontSize: 20,
        fontFamily: 'SFUISemibold',
        color: '#000000',
    },
    reelCardLocationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 5,
        paddingRight: 5,
    }, reelCardContentContainer: {
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        borderRadius: 15,
        padding: 15,
        overflow: 'hidden',
    },
    reelCardLocationText: {
        fontSize: 14,
        fontFamily: 'SFUISemibold',
        color: '#000000',
        marginLeft: 5,
    },
    reelCardFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 15,
    },
    reelCardDistance: {
        fontSize: 16,
        fontFamily: 'SFUISemibold',
        color: '#000000',
    },
    routeButton: {
        backgroundColor: appColors.secondary,
        paddingHorizontal: 20,
        paddingVertical: 8,
        borderRadius: 15,
    },
    routeButtonText: {
        fontSize: 14,
        fontFamily: 'SFUISemibold',
        color: '#ffffff',
    },
    destinationSection: {
        marginBottom: 20,
    },
    destCard: {
        width: 180,
        height: 200,
        marginRight: 15,
    },
    destCardImage: {
        width: '100%',
        height: '100%',
    },
    bookmarkButton: {
        position: 'absolute',
        top: 15,
        right: 15,
        backgroundColor: 'rgba(0,0,0,0.3)',
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
    },
});